### ISSUE TITLE
DefaultEdgeType 

### ISSUE THREAD

**Issue by teajaysee** [fallin/gexf-dotnet#1]
Thank you for the project . i have the following two items set but they don't seem to make their way into the xml.
	gexf.Graph.DefaultEdgeType = GexfEdgeType.Undirected;
	gexf.Graph.Mode = GexfModeType.Static;

**Comment by fallin** [comment]
Those attribute values do not get written-out because they match the defaults for the graph element (according to the spec) and should not be necessary. Are you running into issues with an application misinterpreting these properties when they are missing?

1. It may avoid confusion just to include those attribute values even if they match the defaults.
2. Or maybe there should be a property to determine whether they should be written (roughly similar to the [Newtonsoft.Json's DefaultValueHandling] serialization setting (https://www.newtonsoft.com/json/help/html/SerializationSettings.htm#DefaultValueHandling) that allows specifying "Include" or "Ignore".

**Comment by fallin** [comment]
There's new default value handling options in v0.2.0 that I believe will give more intuitive results. See the change log for details.
